gameday-desktop/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get "static/index"
  get "dashboard", to: "static#dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "static#index"

  namespace :turbo do
    namespace :ios do
      resource :path_configuration, only: [:show]
    end
  end
end

gameday-desktop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

gameday-desktop/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

gameday-desktop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

gameday-desktop/app/controllers/static_controller.rb
class StaticController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]
  def index
  end

  def dashboard
  end
end

gameday-desktop/app/controllers/turbo/ios/path_configurartions_controller.rb
module Turbo
  module Ios
    class PathConfigurationsController < ApplicationController
      def show
        render json: {
          "rules": [
            {
              "patterns": [
                "/new$",
                "/edit$",
                "/sign_in",
                "/sign_up"
              ],
              "properties": {
                "context": "modal"
              }
            }
          ]
        }
      end
    end
  end
end

gameday-desktop/app/controllers/turbo/ios/path_configurations_controller.rb
module Turbo
  module Ios
    class PathConfigurationsController < ApplicationController
      def show
        render json: {
          "rules": [
            {
              "patterns": [
                "/new$",
                "/edit$",
                "/sign_in",
                "/sign_up"
              ],
              "properties": {
                "context": "modal"
              }
            }
          ]
        }
      end
    end
  end
end

gameday-desktop/app/helpers/application_helper.rb
module ApplicationHelper
end

gameday-desktop/app/helpers/static_helper.rb
module StaticHelper
end

gameday-desktop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Gameday Desktop" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to "Home", root_path %>
    <%= link_to "Dashboard", dashboard_path %>
    <% if signed_in? %>
      <%= link_to current_user.email, edit_user_registration_path %>
      <%= button_to "Log out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Log in", new_user_session_path %>
      <%= link_to "Register", new_user_registration_path %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>